apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sairajg8/DevSecOps-GitOps-Supply-Chain-Project.git
    targetRevision: main
    path: deploy/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true