apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

images:
  - name: devsecops-demo
    newName: ghcr.io/sairajg8/devsecops-gitops-supply-chain-project/devsecops-demo
    newTag: latest